### ISSUE TITLE
同样用法 同样的写法 在一个activity中数据加载成功后 loading消失，内容出现，另一个loading消失，不出现内容，出现一个空白页面

### ISSUE THREAD

**Issue by zzzsssbo** [alibaba/StateManager#1]
同样用法 同样的写法 在一个activity中数据加载成功后 loading消失，内容出现，另一个loading消失，不出现内容，出现一个空白页面，我没找到原因

**Comment by zhuitian90** [comment]
同一个页面放置了2个StateLayout,有一个没显示内容吗，能发一下相关代码吗
